Repository Macdeal/vehikl-app, pull requests merged in 2023-10, with the labels that each got.

#2 update: update readme
  README.md
Labels: documentation

#4 update: update readme
  README.md
Labels: documentation

#5 chore: initial project commit
  .eslintrc.cjs
  .gitignore
  README.md
  index.html
  package-lock.json
  package.json
  postcss.config.js
  public/vite.svg
  src/App.tsx
  src/assets/react.svg
  src/index.css
  src/main.tsx
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: feature

#22 feat(issue-21):implemention of event-card
  src/component/EventCard.tsx
  src/pages/HomePage.tsx
Labels: feature

#27 chore(issue-26): altering npm run lint:fix on script in package
  package.json
Labels: chore

#29 feat(issue-21): implementation of event card
  package-lock.json
  package.json
  src/component/EventCard.tsx
  src/components/eventTitle/EventTitle.tsx
  src/container/EventCard.tsx
  src/data.ts
  src/pages/HomePage.tsx
  tsconfig.json
Labels: feature

#31 feat(issue-30):implement event-card collection
  src/components/EventTitle.tsx
  src/container/EventCard.tsx
  src/container/EventCardCollection.tsx
  src/data.ts
  src/pages/HomePage.tsx
Labels: feature, for review

#33 feat: implement button component
  package-lock.json
  src/App.tsx
  src/assets/homepage/arrow-right.svg
  src/components/Button/Button.tsx
  tailwind.config.js
Labels: feature, for review

#34 Header
  src/components/Header/Header.tsx
  src/index.css
  tailwind.config.js
Labels: feature, for review

#38 feat: footer
  src/assets/footer/facebook.svg
  src/assets/footer/instagram.svg
  src/assets/footer/linkedIn.svg
  src/assets/footer/podcast.svg
  src/assets/footer/twitter.svg
  src/assets/footer/youtube.svg
  src/components/Footer/Footer.tsx
  src/components/Footer/index.ts
  src/dummydata/Footer.ts
  src/index.css
  src/pages/HomePage.tsx
Labels: feature, for review
